using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// ScriptableObject — maps each character model prefab to its pre-rendered
/// portrait Sprite.  Portraits are generated by the PortraitCaptureEditor
/// tool (Window → Hooligan → Portrait Capture Tool) and saved as PNG assets.
///
/// Create via:  Assets → Create → Hooligan → Character Portrait Registry
/// </summary>
[CreateAssetMenu(menuName = "Hooligan/Character Portrait Registry",
                 fileName = "CharacterPortraitRegistry")]
public class CharacterPortraitRegistry : ScriptableObject
{
    // ── Entry ─────────────────────────────────────────────────────────────

    [System.Serializable]
    public class Entry
    {
        [Tooltip("The character model prefab — must match the prefabs added to the Portrait Capture Tool.")]
        public GameObject modelPrefab;
        [Tooltip("Generated reduced-mesh variant. Original source model is preserved.")]
        public GameObject optimizedModelPrefab;
        [HideInInspector] public string sourceModelAssetPath;

        [Tooltip("Animator Controller to use for this model at runtime (battle idle/run/attack). " +
                 "If null, BattleManager.characterAnimator is used as a fallback.")]
        public RuntimeAnimatorController animatorController;

        [Tooltip("Pre-rendered portrait Sprite generated by the Portrait Capture Tool.")]
        public Sprite portrait;
    }

    // ── Data ──────────────────────────────────────────────────────────────

    [Tooltip("One entry per character model. Order does not matter — lookup is by prefab reference.")]
    public List<Entry> entries = new List<Entry>();

    // ── Lookup API ────────────────────────────────────────────────────────

    /// <summary>
    /// Returns the portrait Sprite for a given model prefab.
    /// Returns null if no matching entry is found.
    /// </summary>
    public Sprite GetPortrait(GameObject modelPrefab)
    {
        if (modelPrefab == null) return null;
        foreach (var e in entries)
            if (e.modelPrefab == modelPrefab) return e.portrait;
        return null;
    }

    /// <summary>
    /// Returns the portrait Sprite by index into the entries list.
    /// Safe — returns null if index is out of range.
    /// </summary>
    public Sprite GetPortraitByIndex(int index)
    {
        if (index < 0 || index >= entries.Count) return null;
        return entries[index].portrait;
    }
}
